-- Enable the pgvector extension for vector similarity search
CREATE EXTENSION IF NOT EXISTS vector;

-- Create the documents table
CREATE TABLE IF NOT EXISTS documents (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  content TEXT NOT NULL,
  metadata JSONB DEFAULT '{}'::JSONB,
  embedding vector(1536),  -- OpenAI text-embedding-3-small produces 1536-dimensional vectors
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Create an index on the embedding column for faster similarity search
CREATE INDEX IF NOT EXISTS documents_embedding_idx ON documents
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Create an index on created_at for faster sorting
CREATE INDEX IF NOT EXISTS documents_created_at_idx ON documents(created_at DESC);

-- Create a function to search for similar documents
CREATE OR REPLACE FUNCTION match_documents(
  query_embedding vector(1536),
  match_threshold FLOAT DEFAULT 0.7,
  match_count INT DEFAULT 5
)
RETURNS TABLE (
  id UUID,
  content TEXT,
  metadata JSONB,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    documents.id,
    documents.content,
    documents.metadata,
    1 - (documents.embedding <=> query_embedding) AS similarity
  FROM documents
  WHERE 1 - (documents.embedding <=> query_embedding) > match_threshold
  ORDER BY documents.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- Create a function to update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc'::TEXT, NOW());
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Create a trigger to automatically update updated_at
CREATE TRIGGER update_documents_updated_at BEFORE UPDATE ON documents
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Insert some sample documents (optional)
-- Uncomment the lines below to add sample data

-- INSERT INTO documents (content, metadata, embedding) VALUES
-- ('Visma is a leading provider of business software solutions in Europe.',
--  '{"category": "company", "title": "About Visma"}',
--  NULL), -- Embedding will be generated by the application
-- ('Our solutions help businesses streamline their operations and improve efficiency.',
--  '{"category": "products", "title": "Product Overview"}',
--  NULL);

-- Grant necessary permissions (adjust based on your RLS policies)
-- ALTER TABLE documents ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow authenticated users to read documents
-- CREATE POLICY "Allow authenticated users to read documents" ON documents
-- FOR SELECT TO authenticated USING (true);

-- Create a policy to allow authenticated users to insert documents
-- CREATE POLICY "Allow authenticated users to insert documents" ON documents
-- FOR INSERT TO authenticated WITH CHECK (true);

COMMENT ON TABLE documents IS 'Stores documents with their vector embeddings for RAG search';
COMMENT ON COLUMN documents.embedding IS 'Vector embedding generated by OpenAI text-embedding-3-small (1536 dimensions)';
COMMENT ON FUNCTION match_documents IS 'Searches for similar documents using cosine similarity on vector embeddings';
